export { ListaArea } from './ListaArea'
export { ListaEmpleado } from './ListaEmpleado'
export { About } from './About'
export { NotFound } from './NotFound'
export { AltaEmpleado } from './AltaEmpleado'
export { Login } from './Login'
export { Registro } from './Registro'
