export { EmpleadosList } from "./EmpleadosList"
export { About } from "./About"
export { NotFound } from "./NotFound"
export { AreasList } from "./AreasList"
export { AltaEmpleado } from "./AltaEmpleado"